### ISSUE TITLE
Clarification regarding GSOC and GCI

### ISSUE THREAD

**Issue by hackerkid** [tapaswenipathak/Open-Source-Programs#63]
Since the description of this repo is **A list of open source internship programs.** I would like to point out that that GSOC is [not considered as an Internship]( https://developers.google.com/open-source/gsoc/faq). I think there must be some other programs as well which are not considered as Internship so you should probably consider editing the description.

Also, I think GCI should come under **Open Source Competitions** as [it is is a contest](https://codein.withgoogle.com/archive/) to introduce pre-university students (ages 13-17) to open source software development and gives prizes for winners.

**Comment by palash25** [comment]
Agreed @hackerkid 
Can you make a PR to move GCI to the competitions section if you have some time?

The description needs to be changed to that can only be done by @tapasweni-pathak

**Comment by sakshivij** [comment]
GSOC is not considered an internship but an activity that the student performs as an independent developer. The description of this repo should be changed to **A list of open source programs**
@tapaswenipathak what do you think? 

Also, major part of this issue is resolved, it should be closed I assume.
